In [1]:
from ipywidgets import Image
from ipywidgets import ColorPicker, IntSlider, link, AppLayout, HBox
from ipycanvas import RoughCanvas, Canvas, hold_canvas

from IPython.display import display

import importlib
import numpy as np
from numpy import linalg as LA
import itertools

from src import *
from src import classification
from src import interpretation

In [2]:
width = 900
height = 900

In [3]:
#Set up canvas
canvas = Canvas(width=width, height=height)

drawing = False
position = None
points = np.zeros((2,0))
shape = []


def on_mouse_down(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = True
    position = (x, y)
    shape = [position]


def on_mouse_move(x, y):
    global drawing
    global position
    global shape
    global points

    if not drawing:
        return

    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)

        position = (x, y)

    shape.append(position)


def on_mouse_up(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = False
    
    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)
    
    points = np.append(points,shape)

    shape = []


canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

canvas.stroke_style = '#000000'

canvas.scale = 10
canvas.layout.border_width = 3
canvas.layout.border = 'solid'
canvas.layout.border_color = '#000000'

In [4]:
# Draw on this to get stroke
points = np.zeros((2,0))

canvas

Canvas(height=900, layout=Layout(border='solid'), width=900)

In [5]:
importlib.reload(classification)
points = points.reshape((-1,2))

seg_pts, c_list, a_list, _ = findSegmentationPoints(points)

for segment in seg_pts:
    print(classification.classify(segment))

(array([9.99923220e-01, 7.55115325e-03, 4.45710506e-06, 9.99981805e-01]), {'vertex': {'center': array([442.89114238, 209.09043874]), 'radius': 13.916151383564804}, 'edge': array([[291.61837748, 127.80422185],
       [293.60513245, 154.62541391],
       [300.55877483, 131.77773179]]), 'loop': array([[291.61837748, 127.80422185],
       [279.69784768, 145.68501656],
       [293.60513245, 154.62541391],
       [301.55215232, 139.72475166],
       [300.55877483, 131.77773179]]), 'triangle': {'a': array([279.69784768, 148.66514901]), 'b': array([291.61837748, 127.80422185]), 'c': array([293.60513245, 154.62541391])}})
(array([2.45271696e-05, 7.66458420e-04, 9.99533996e-01, 3.79248098e-03]), {'vertex': {'center': array([499.84147351, 234.15335265]), 'radius': 76.7167995030715}, 'edge': array([[296.5852649 , 128.79759934],
       [308.59188742, 156.77110927],
       [344.57201987, 183.75786424],
       [377.57201987, 199.75786424],
       [415.45281457, 210.71150662],
       [418.43294702, 21

In [6]:
importlib.reload(interpretation)

<module 'src.interpretation' from '/Users/riksanyal/Desktop/graph-recognition/src/interpretation.py'>

In [7]:
interpretation.recog(points,[],-1.3,0.2,-0.6)

(-1.1008752147778154,
 [[['vertex', [442.89114238410593, 209.09043874172187], 13.916151383564804],
   ['loop',
    [array([296.5852649 , 128.79759934]),
     array([296.625     , 141.80422185]),
     array([308.59188742, 156.77110927]),
     array([324.59188742, 169.77110927]),
     array([344.57201987, 183.75786424]),
     array([357.57201987, 190.75786424]),
     array([377.57201987, 199.75786424]),
     array([397.57201987, 203.75786424]),
     array([415.45281457, 210.71150662]),
     array([418.43294702, 212.69826159])]],
   ['vertex', [656.9639900662252, 341.7063327814569], 12.663127931107901]],
  [['vertex', [442.89114238410593, 209.09043874172187], 13.916151383564804],
   ['loop',
    [array([296.5852649 , 128.79759934]),
     array([296.625     , 141.80422185]),
     array([308.59188742, 156.77110927]),
     array([324.59188742, 169.77110927]),
     array([344.57201987, 183.75786424]),
     array([357.57201987, 190.75786424]),
     array([377.57201987, 199.75786424]),
     arr