In [1]:
from ipywidgets import Image
from ipywidgets import ColorPicker, IntSlider, link, AppLayout, HBox
from ipycanvas import RoughCanvas, Canvas, hold_canvas

from IPython.display import display

import importlib
import numpy as np
from numpy import linalg as LA
import itertools

from src import *
from src import classification
from src import interpretation

In [2]:
width = 900
height = 900

In [3]:
#Set up canvas
canvas = Canvas(width=width, height=height)

drawing = False
position = None
points = np.zeros((2,0))
shape = []


def on_mouse_down(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = True
    position = (x, y)
    shape = [position]


def on_mouse_move(x, y):
    global drawing
    global position
    global shape
    global points

    if not drawing:
        return

    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)

        position = (x, y)

    shape.append(position)


def on_mouse_up(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = False
    
    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)
    
    points = np.append(points,shape)

    shape = []


canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

canvas.stroke_style = '#000000'

canvas.scale = 10
canvas.layout.border_width = 3
canvas.layout.border = 'solid'
canvas.layout.border_color = '#000000'

In [4]:
# Draw on this to get stroke
points = np.zeros((2,0))

canvas

Canvas(height=900, layout=Layout(border='solid'), width=900)

In [5]:
importlib.reload(classification)
points = points.reshape((-1,2))

seg_pts, c_list, a_list, _ = findSegmentationPoints(points)

for segment in seg_pts:
    print(classification.classify(segment))

(array([0.94425369, 0.01262079, 0.00296467, 0.99024422]), {'vertex': {'center': array([413.08981788, 119.18977649]), 'radius': 24.82450132370821}, 'edge': array([[276.71771523,  79.12872517],
       [278.7044702 ,  91.04925497],
       [276.71771523,  54.29428808],
       [296.5852649 ,  69.19495033],
       [282.67798013,  83.1022351 ]]), 'loop': array([[276.71771523,  79.12872517],
       [264.79718543,  90.05587748],
       [278.7044702 ,  91.04925497],
       [272.7442053 ,  73.16846026],
       [276.71771523,  54.29428808],
       [292.61175497,  52.30753311],
       [296.5852649 ,  69.19495033],
       [282.67798013,  83.1022351 ]]), 'triangle': {'a': array([288.63824503,  49.32740066]), 'b': array([292.61175497,  75.15521523]), 'c': array([274.73096026,  56.28104305])}})
(array([7.31437341e-06, 9.11577163e-01, 9.84298617e-01, 2.12666591e-05]), {'vertex': {'center': array([425.54677152, 174.40169702]), 'radius': 43.95780109184219}, 'edge': array([[268.77069536,  91.04925497],
   

In [9]:
importlib.reload(interpretation)

<module 'src.interpretation' from '/Users/riksanyal/Desktop/graph-recognition/src/interpretation.py'>

In [10]:
interpretation.recog(points,[],-1.3,0.2,-0.6)

[[['vertex', [413.0898178807947, 119.18977649006622], 24.82450132370821],
  ['loop',
   [array([268.77069536,  91.04925497]),
    array([280.71771523, 113.94991722]),
    array([287.71109272, 127.93667219]),
    array([298.65149007, 145.84395695]),
    array([310.57201987, 162.73137417]),
    array([313.55215232, 166.70488411])]],
  ['vertex', [482.6262417218543, 274.1566639072847], 10.629603257797708],
  ['edge',
   [array([312.47930464, 170.51945364]),
    array([322.41307947, 156.61216887])]]],
 [['vertex', [413.0898178807947, 119.18977649006622], 24.82450132370821],
  ['edge',
   [array([268.77069536,  91.04925497]),
    array([287.71109272, 127.93667219]),
    array([310.57201987, 162.73137417]),
    array([313.55215232, 166.70488411])]],
  ['vertex', [482.6262417218543, 274.1566639072847], 10.629603257797708],
  ['edge',
   [array([312.47930464, 170.51945364]),
    array([322.41307947, 156.61216887])]]],
 [['triangle',
   [288.6382450331126, 49.327400662251655],
   [292.611754966

In [14]:
interpretation.recog(points,[],-1.3,0.2,-0.6)[0]

[['vertex', [413.0898178807947, 119.18977649006622], 24.82450132370821],
 ['loop',
  [array([268.77069536,  91.04925497]),
   array([280.71771523, 113.94991722]),
   array([287.71109272, 127.93667219]),
   array([298.65149007, 145.84395695]),
   array([310.57201987, 162.73137417]),
   array([313.55215232, 166.70488411])]],
 ['vertex', [482.6262417218543, 274.1566639072847], 10.629603257797708],
 ['edge',
  [array([312.47930464, 170.51945364]), array([322.41307947, 156.61216887])]]]