In [1]:
from ipywidgets import Image
from ipywidgets import ColorPicker, IntSlider, link, AppLayout, HBox
from ipycanvas import RoughCanvas, Canvas, hold_canvas

from IPython.display import display

import importlib
import numpy as np
import itertools

from src import *
from src import classification
from src import interpretation

In [2]:
width = 900
height = 900

In [3]:
#Set up canvas
canvas = Canvas(width=width, height=height)

drawing = False
position = None
points = np.zeros((2,0))
shape = []


def on_mouse_down(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = True
    position = (x, y)
    shape = [position]


def on_mouse_move(x, y):
    global drawing
    global position
    global shape
    global points

    if not drawing:
        return

    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)

        position = (x, y)

    shape.append(position)


def on_mouse_up(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = False
    
    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)
    
    points = np.append(points,shape)

    shape = []


canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

canvas.stroke_style = '#000000'

canvas.scale = 10
canvas.layout.border_width = 3
canvas.layout.border = 'solid'
canvas.layout.border_color = '#000000'

In [4]:
# Draw on this to get stroke
points = np.zeros((2,0))

canvas

Canvas(height=900, layout=Layout(border='solid'), width=900)

In [5]:
importlib.reload(classification)
points = points.reshape((-1,2))

seg_pts, c_list, a_list, _ = findSegmentationPoints(points)

for segment in seg_pts:
    print(classification.classify(segment))

(array([2.01356752e-04, 9.99902716e-01, 7.33364820e-02, 3.99779611e-05]), {'vertex': {'center': array([533.78518212, 244.85202815]), 'radius': 11.722275219741013}, 'edge': array([[362.14817881, 158.59892384],
       [343.27400662, 172.50620861]]), 'loop': array([[362.14817881, 158.59892384],
       [344.26738411, 170.51945364],
       [343.27400662, 172.50620861]]), 'triangle': {'a': 4, 'b': 0, 'c': 2}})
(array([0.08413084, 0.97628059, 0.00269642, 0.08350238]), {'vertex': {'center': array([528.8182947 , 258.26262417]), 'radius': 16.806878459293337}, 'edge': array([[343.27400662, 178.46647351],
       [371.08857616, 163.56581126],
       [369.10182119, 157.60554636]]), 'loop': array([[343.27400662, 178.46647351],
       [364.13493377, 179.45985099],
       [371.08857616, 163.56581126],
       [369.10182119, 157.60554636]]), 'triangle': {'a': 9, 'b': 0, 'c': 4}})
(array([8.10912675e-05, 8.54433801e-02, 9.77666399e-01, 2.15762273e-03]), {'vertex': {'center': array([550.19577815, 287.72620

In [8]:
interpretation.recog(points,[],1,2,3)

[[['triangle', [4], [0], [2]],
  ['loop',
   [array([343.27400662, 178.46647351]),
    array([364.13493377, 179.45985099]),
    array([371.08857616, 163.56581126]),
    array([369.10182119, 157.60554636])]],
  ['vertex', [550.1957781456954, 287.7262003311258], 54.95367470657423]],
 [['vertex', [533.7851821192053, 244.85202814569539], 11.722275219741013],
  ['loop',
   [array([343.27400662, 178.46647351]),
    array([364.13493377, 179.45985099]),
    array([371.08857616, 163.56581126]),
    array([369.10182119, 157.60554636])]],
  ['vertex', [550.1957781456954, 287.7262003311258], 54.95367470657423]],
 [['triangle', [4], [0], [2]],
  ['loop',
   [array([343.27400662, 178.46647351]),
    array([364.13493377, 179.45985099]),
    array([371.08857616, 163.56581126]),
    array([369.10182119, 157.60554636])]],
  ['triangle', [10], [1], [4]]],
 [['vertex', [533.7851821192053, 244.85202814569539], 11.722275219741013],
  ['loop',
   [array([343.27400662, 178.46647351]),
    array([364.13493377,

In [9]:
points = np.zeros((2,0))

canvas

Canvas(height=900, layout=Layout(border='solid'), width=900)

In [10]:
importlib.reload(classification)
points = points.reshape((-1,2))

seg_pts = findSegmentationPoints(points)[0]

for segment in seg_pts:
    print(classification.classify(segment))

(array([1.47961227e-06, 9.76254659e-01, 9.87785759e-01, 5.30598937e-06]), {'vertex': {'center': array([650.38120861, 230.50144868]), 'radius': 47.08873233349735}, 'edge': array([[371.08857616, 159.65438742],
       [418.01572848, 153.66100993],
       [456.88990066, 150.67425497],
       [464.83692053, 150.67425497]]), 'loop': array([[371.08857616, 159.65438742],
       [396.01572848, 156.66100993],
       [418.01572848, 153.66100993],
       [434.00248344, 151.66763245],
       [456.88990066, 150.67425497],
       [464.83692053, 150.67425497]]), 'triangle': {'a': 4, 'b': 0, 'c': 2}})
(array([9.99987835e-01, 1.43923512e-03, 2.77210445e-06, 9.99997424e-01]), {'vertex': {'center': array([726.50041391, 232.52793874]), 'radius': 12.913907284768214}, 'edge': array([[475.39321192, 147.73385762],
       [487.31374172, 163.62789735],
       [474.39983444, 145.74710265]]), 'loop': array([[475.39321192, 147.73385762],
       [468.43956954, 161.64114238],
       [487.31374172, 163.62789735],
    