In [1]:
from ipywidgets import Image
from ipywidgets import ColorPicker, IntSlider, link, AppLayout, HBox
from ipycanvas import RoughCanvas, Canvas, hold_canvas

from IPython.display import display

import importlib
import numpy as np
from numpy import linalg as LA
import itertools

from src import *
from src import classification
from src import interpretation

In [2]:
width = 900
height = 900

In [16]:
#Set up canvas
canvas = Canvas(width=width, height=height)

drawing = False
position = None
points = np.zeros((2,0))
shape = []


def on_mouse_down(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = True
    position = (x, y)
    shape = [position]


def on_mouse_move(x, y):
    global drawing
    global position
    global shape
    global points

    if not drawing:
        return

    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)

        position = (x, y)

    shape.append(position)


def on_mouse_up(x, y):
    global drawing
    global position
    global shape
    global points

    drawing = False
    
    with hold_canvas(canvas):
        canvas.stroke_line(position[0], position[1], x, y)
    
    points = np.append(points,shape)

    shape = []


canvas.on_mouse_down(on_mouse_down)
canvas.on_mouse_move(on_mouse_move)
canvas.on_mouse_up(on_mouse_up)

canvas.stroke_style = '#000000'

canvas.scale = 10
canvas.layout.border_width = 3
canvas.layout.border = 'solid'
canvas.layout.border_color = '#000000'

In [17]:
# Draw on this to get stroke
points = np.zeros((2,0))

canvas

Canvas(height=900, layout=Layout(border='solid'), width=900)

In [18]:
importlib.reload(classification)
points = points.reshape((-1,2))

seg_pts, c_list, a_list, _ = findSegmentationPoints(points)

for segment in seg_pts:
    print(classification.classify(segment))

(array([9.99971196e-01, 7.33596894e-03, 2.33336087e-06, 9.99990807e-01]), {'vertex': {'center': array([388.25538079, 222.50103477]), 'radius': 11.028279790318473}, 'edge': array([[259.83029801, 133.76448675],
       [263.80380795, 151.64528146],
       [260.8236755 , 136.74461921]]), 'loop': array([[259.83029801, 133.76448675],
       [248.9031457 , 147.67177152],
       [263.80380795, 151.64528146],
       [260.8236755 , 136.74461921]]), 'triangle': {'a': array([265.79056291, 142.70488411]), 'b': array([256.85016556, 155.61879139]), 'c': array([251.88327815, 135.75124172])}})
(array([1.08190237e-03, 3.61653128e-05, 9.91124387e-01, 3.61161881e-01]), {'vertex': {'center': array([459.99048013, 197.22288907]), 'radius': 74.876647534126}, 'edge': array([[256.85016556, 134.75786424],
       [282.80380795, 163.73137417],
       [321.68460265, 182.67839404],
       [358.4660596 , 177.69163907],
       [391.37996689, 150.75786424],
       [406.28062914, 124.93004967]]), 'loop': array([[256.850

In [19]:
importlib.reload(interpretation)

<module 'src.interpretation' from '/Users/riksanyal/Desktop/graph-recognition/src/interpretation.py'>

In [20]:
interpretation.recog(points,[],-1.3,0.2,-0.6)

[[['vertex', [388.255380794702, 222.50103476821192], 11.028279790318473],
  ['loop',
   [array([256.85016556, 134.75786424]),
    array([269.80380795, 154.73137417]),
    array([282.80380795, 163.73137417]),
    array([301.79056291, 174.71812914]),
    array([321.68460265, 182.67839404]),
    array([337.57864238, 183.67177152]),
    array([358.4660596 , 177.69163907]),
    array([373.41970199, 167.71812914]),
    array([391.37996689, 150.75786424]),
    array([400.32036424, 136.85057947]),
    array([406.28062914, 124.93004967])]],
  ['vertex', [630.6394867549669, 187.23613410596028], 13.556964301943228]],
 [['vertex', [388.255380794702, 222.50103476821192], 11.028279790318473],
  ['triangle',
   [262.8501655629139, 150.7578642384106],
   [256.8501655629139, 134.7578642384106],
   [346.5190397350993, 182.6783940397351]],
  ['vertex', [630.6394867549669, 187.23613410596028], 13.556964301943228]],
 [['triangle',
   [265.7905629139073, 142.70488410596028],
   [256.8501655629139, 155.61879